# Generated by Django 5.1.4 on 2025-02-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_date_added_lead_description_lead_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='leads_count',
            field=models.IntegerField(default=0),
        ),
    ]
